-- Canonical Entity Autocomplete System — Drive corpus import (entity batch 1).
-- Source: "ORYN Canonical App Data Pack — Verified 2026-08-15" (Google Sheet, ORYN Database Drive folder) —
-- the current, non-superseded canonical data pack. Generated by
-- scripts/drive-import/parse_entities.py + generate_entities_sql.py; see
-- scripts/drive-import/README.md for the process and docs/entity-canonicalization-audit.md
-- for what this batch does and does not attempt.
--
-- Requires supabase/migrations/0038_canonical_institutions.sql applied first (this
-- file's ON CONFLICT clauses depend on its unique indexes). Not applied to any live
-- database this session — see docs/founder-blocked-backlog.md item 17.
--
-- Idempotent: every insert/update is safe to re-run.

-- ---------- Organizations (PROV, 19 rows, all release_state=VERIFIED) ----------
insert into public.institutions (category, canonical_name, institution_type, country, city, website_url, aliases, status, source)
values
  ('organization', 'London International Youth Science Forum', 'nonprofit_program_provider', 'United Kingdom', null, 'https://liysf.org.uk', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0001)'),
  ('organization', 'Yale University', 'university', 'United States', null, 'https://yale.edu', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0002)'),
  ('organization', 'Breakthrough Prize Foundation', 'foundation', 'United States', null, 'https://breakthroughjuniorchallenge.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0003)'),
  ('organization', 'Conrad Foundation', 'foundation', 'United States', null, 'https://conrad.spacecenter.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0004)'),
  ('organization', 'University of Delaware Horn Entrepreneurship', 'university_center', 'United States', null, 'https://diamondchallenge.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0005)'),
  ('organization', 'Blue Ocean Competition', 'competition_provider', 'United States', null, 'https://blueoceancompetition.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0006)'),
  ('organization', 'Immerse Education', 'education_provider', 'United Kingdom', null, 'https://immerse.education', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0007)'),
  ('organization', 'Summer Science Program', 'nonprofit_program_provider', 'United States', null, 'https://ssp.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0008)'),
  ('organization', 'PROMYS', 'academic_program', 'United States', null, 'https://promys.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0009)'),
  ('organization', 'Journal of Emerging Investigators', 'journal', 'United States', null, 'https://emerginginvestigators.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0010)'),
  ('organization', 'The Concord Review', 'journal', 'United States', null, 'https://tcr.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0011)'),
  ('organization', 'Phillips Academy', 'school', 'United States', null, 'https://andover.edu', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0012) — Andover Summer provider'),
  ('organization', 'Acıbadem University', 'university', 'Turkey', null, 'https://acibadem.edu.tr', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0013)'),
  ('organization', 'Carnegie Mellon University', 'university', 'United States', null, 'https://cmu.edu', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0014)'),
  ('organization', 'AwesomeMath', 'education_provider', 'United States', null, 'https://awesomemath.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0015)'),
  ('organization', 'Harvard-MIT Mathematics Tournament', 'student_run_competition', 'United States', null, 'https://hmmt.org', array['HMMT'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0016) — Organized by students at Harvard, MIT and nearby schools.'),
  ('organization', 'The Earth Foundation', 'foundation', 'Switzerland', null, 'https://theearthprize.org', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0017) — Website terms identify The Earth Foundation, Geneva, Switzerland, as owner/operator.'),
  ('organization', 'Wharton Global Youth Program', 'university_program', 'United States', null, 'https://globalyouth.wharton.upenn.edu', '{}', 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0018) — Wharton School, University of Pennsylvania.'),
  ('organization', 'Mathematical Association of America', 'professional_association', 'United States', null, 'https://maa.org', array['MAA'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (PROV-0019) — Organizer of the American Mathematics Competitions.')
on conflict (category, lower(canonical_name), coalesce(country, ''), coalesce(city, '')) do nothing;

-- ---------- Schools (TRSCH, 54 of 58 rows — 4 excluded: release_state starts with HOLD_, not yet safe to surface) ----------
insert into public.institutions (category, canonical_name, institution_type, country, city, website_url, aliases, status, source)
values
  ('school', 'Üsküdar American Academy', 'high_school', 'Turkey', 'İstanbul', 'https://www.uaa.k12.tr/', array['Üsküdar Amerikan Lisesi', 'UAA', 'Uskudar American Academy'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0001) — Official school + IB directory'),
  ('school', 'Robert College', 'high_school', 'Turkey', 'İstanbul', 'https://website.robcol.k12.tr/', array['Robert Kolej', 'RC'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0002) — Official school'),
  ('school', 'The Koç School', 'high_school', 'Turkey', 'İstanbul', 'https://www.koc.k12.tr/', array['Koç School'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0003) — Official school + IB directory'),
  ('school', 'ENKA Schools Istanbul', 'high_school', 'Turkey', 'İstanbul', 'https://www.enka.k12.tr/istanbul/', array['ENKA Okulları İstanbul'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0004) — Official school + IB directory'),
  ('school', 'American Collegiate Institute', 'high_school', 'Turkey', 'İzmir', 'https://www.aci.k12.tr/', array['İzmir Amerikan Koleji', 'ACI'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0005) — Official school + IB directory'),
  ('school', 'Tarsus American College', 'high_school', 'Turkey', 'Mersin', 'https://www.tac.k12.tr/', array['Tarsus Amerikan Koleji', 'TAC'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0006) — Official school + IB directory'),
  ('school', 'Hisar School', 'high_school', 'Turkey', 'İstanbul', 'https://www.hisarschool.k12.tr/', array['Hisar Okulları'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0007) — Official school'),
  ('school', 'TED Ankara College Foundation High School', 'high_school', 'Turkey', 'Ankara', 'https://www.tedankara.k12.tr/', array['TED Ankara Koleji'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0008) — Official school + IB directory'),
  ('school', 'İstanbul Özel Saint-Joseph Fransız Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://sj.k12.tr/', array['Saint Joseph Lisesi', 'Saint-Joseph', 'SJ'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0009) — Official school'),
  ('school', 'Deutsche Schule Istanbul', 'high_school', 'Turkey', 'İstanbul', 'https://www.ds-istanbul.net/', array['Alman Lisesi', 'DSI', 'Özel Alman Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0010) — Official school + German Federal Foreign Office'),
  ('school', 'Galatasaray Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://gsl.gsu.edu.tr/', array['Galatasaray High School', 'GSL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0011) — Official school'),
  ('school', 'Kabataş Erkek Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://kabataserkeklisesi.meb.k12.tr/', array['Kabataş Lisesi', 'KEL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0012) — MEB official + IB'),
  ('school', 'İstanbul Erkek Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://istanbulerkeklisesi.meb.k12.tr/', array['IEL', 'Istanbul High School', 'İstanbul Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0013) — MEB + German Federal Foreign Office'),
  ('school', 'Saint Benoît Fransız Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.sb.k12.tr/', array['Saint Benoît', 'Saint Benoit Fransız Lisesi', 'SB'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0014) — Official school'),
  ('school', 'Sainte Pulchérie Fransız Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.sp.k12.tr/', array['Sainte Pulchérie', 'Sainte Pulcherie Fransız Lisesi', 'SP'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0015) — Official school'),
  ('school', 'Özel Saint-Michel Fransız Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://sm.k12.tr/', array['Saint Michel Fransız Lisesi', 'Saint-Michel', 'SM'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0016) — Official school'),
  ('school', 'İzmir Özel Saint-Joseph Fransız Lisesi', 'high_school', 'Turkey', 'İzmir', 'https://izmirsj.k12.tr/', array['ISJ', 'İzmir Saint Joseph Fransız Lisesi', 'İzmir Saint-Joseph'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0017) — Official school'),
  ('school', 'İELEV Özel Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.ielev.k12.tr/', array['IELEV', 'İELEV Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0018) — Official school + German authorities'),
  ('school', 'ALKEV Özel Anadolu ve Fen Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.alkev.k12.tr/', array['ALKEV', 'ALKEV Özel Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0019) — Official school'),
  ('school', 'Özel Notre Dame de Sion Fransız Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://nds.k12.tr/', array['Lycée Français Notre Dame de Sion', 'NDS', 'Notre Dame de Sion'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0020) — Official school-controlled sources'),
  ('school', 'Vefa Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://vefalisesi.meb.k12.tr/', array['Vefa High School', 'VL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0021) — MEB + International Baccalaureate'),
  ('school', 'Cağaloğlu Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://cagalogluanadolulisesi.meb.k12.tr/', array['Cagaloglu Anadolu Lisesi', 'CAL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0022) — MEB official'),
  ('school', 'Ankara Özel Tevfik Fikret Lisesi', 'high_school', 'Turkey', 'Ankara', 'https://ankara.tfo.k12.tr/', array['Ankara Tevfik Fikret Lisesi', 'Ankara TFL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0023) — Official school'),
  ('school', 'İzmir Özel Tevfik Fikret Anadolu ve Fen Lisesi', 'high_school', 'Turkey', 'İzmir', 'https://izmir.tfo.k12.tr/', array['İzmir Tevfik Fikret Lisesi', 'İzmir TFL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0024) — Official school'),
  ('school', 'Ankara Fen Lisesi', 'high_school', 'Turkey', 'Ankara', 'https://ankarafenlisesi.meb.k12.tr/', array['AFL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0025) — MEB official'),
  ('school', 'Ankara Türk Telekom Sosyal Bilimler Lisesi', 'high_school', 'Turkey', 'Ankara', 'https://asbl.meb.k12.tr/', array['ASBL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0026) — MEB + International Baccalaureate'),
  ('school', 'Beşiktaş Sakıp Sabancı Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://sabancilisesi.meb.k12.tr/', array['Besiktas Sakip Sabanci Anadolu Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0027) — MEB + International Baccalaureate'),
  ('school', 'Çemberlitaş Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://cemberlitasanadolu.meb.k12.tr/', array['Cemberlitas Anadolu Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0028) — MEB + International Baccalaureate'),
  ('school', 'Hüseyin Avni Sözen Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://hasal.meb.k12.tr/', array['HASAL', 'Huseyin Avni Sozen Anatolian High School'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0029) — MEB + International Baccalaureate'),
  ('school', 'Prof. Dr. Mümtaz Turhan Sosyal Bilimler Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://isbl.meb.k12.tr/', array['ISBL', 'Istanbul Prof. Dr. Mümtaz Turhan Sosyal Bilimler Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0030) — MEB + International Baccalaureate'),
  ('school', 'Kartal Anadolu İmam Hatip Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://kartalaihl.meb.k12.tr/', array['Kartal AİHL', 'Kartal Anadolu Imam Hatip Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0031) — MEB + International Baccalaureate'),
  ('school', 'Nilüfer Anadolu İmam Hatip Lisesi', 'high_school', 'Turkey', 'Bursa', 'https://niluferanadoluihl.meb.k12.tr/', array['Nilüfer AİHL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0032) — MEB + International Baccalaureate'),
  ('school', 'Tenzile Erdoğan Kız Anadolu İmam Hatip Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://tenzileerdogankaihl.meb.k12.tr/', array['Tenzile Erdoğan Kız AİHL', 'Tenzile Erdogan Kiz Anadolu Imam Hatip Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0033) — MEB + International Baccalaureate'),
  ('school', 'Uluslararası Murat Hüdavendigar Anadolu İmam Hatip Lisesi', 'high_school', 'Turkey', 'Bursa', 'https://murathudavendigaraihl.meb.k12.tr/', array['Murat Hüdavendigar AİHL'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0034) — MEB + International Baccalaureate'),
  ('school', 'Yeşilköy Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://yesilkoyanadolu.meb.k12.tr/', array['YESILKOY ANADOLU LISESI'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0035) — MEB + International Baccalaureate'),
  ('school', 'SEV American College', 'high_school', 'Turkey', 'İstanbul', 'https://www.sevkoleji.k12.tr/', array['SEV Amerikan Koleji', 'SAC', 'Özel SEV Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0036) — Official school + International Baccalaureate'),
  ('school', 'Bilkent Laboratory and International School', 'high_school', 'Turkey', 'Ankara', 'https://www.blisankara.org/', array['BLIS', 'Bilkent Laboratory International School', 'İDV Bilkent Üniversitesi Laboratuvar Okulu', 'İhsan Doğramacı Vakfı Ankara Okulları'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0037) — Bilkent University + International Baccalaureate'),
  ('school', 'MEF Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.mef.k12.tr/ulus-lisesi/', array['Özel MEF Lisesi', 'MEF High School', 'MEF Ulus Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0038) — Official school + International Baccalaureate'),
  ('school', 'British International School Istanbul', 'high_school', 'Turkey', 'İstanbul', 'https://www.bis.k12.tr/', array['BISI', 'The British International School Istanbul', 'British International School İstanbul'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0039) — Official school + International Baccalaureate'),
  ('school', 'Özel ALEV Okulları', 'high_school', 'Turkey', 'İstanbul', 'https://alev.k12.tr/', array['ALEV Anadolu Lisesi', 'ALEV Okulları', 'Private ALEV Schools'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0040) — Official school + International Baccalaureate'),
  ('school', 'TED Üsküdar Koleji', 'high_school', 'Turkey', 'İstanbul', 'https://www.teduskudar.k12.tr/', array['TED Uskudar Koleji', 'TED Üsküdar'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0041) — Official school + International Baccalaureate'),
  ('school', 'TED Bursa Koleji', 'high_school', 'Turkey', 'Bursa', 'https://www.tedbursa.k12.tr/', array['TED Bursa College', 'TED Bursa Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0042) — Official school + International Baccalaureate'),
  ('school', 'Terakki Vakfı Özel Şişli Terakki Tepeören Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.terakki.org.tr/', array['T.V. Özel Şişli Terakki Tepeören Anadolu Lisesi', 'Tepeören Anadolu Lisesi', 'Terakki Foundation Schools_Tepeoren Campus'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0043) — Official school + International Baccalaureate'),
  ('school', 'İSTEK Ankara Okulları Anadolu Lisesi', 'high_school', 'Turkey', 'Ankara', 'https://ankara.istek.k12.tr/', array['ISTEK Private Ankara Schools', 'İSTEK Ankara Anadolu Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0044) — Official school + International Baccalaureate'),
  ('school', 'İSTEK Acıbadem Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://acibadem.istek.k12.tr/', array['ISTEK Private Acibadem Schools', 'İSTEK Acıbadem Okulları Anadolu Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0045) — Official school + International Baccalaureate'),
  ('school', 'Arı Anadolu Lisesi', 'high_school', 'Turkey', 'Ankara', 'https://www.ariokullari.k12.tr/', array['ARI ANADOLU LİSESİ', 'Arı Private Anatolian High School', 'Özel Arı Anadolu Lisesi'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0046) — Official school + International Baccalaureate'),
  ('school', 'Istanbul International Community School', 'high_school', 'Turkey', 'İstanbul', 'https://www.iics.k12.tr/', array['IICS', 'İstanbul International Community School'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0047) — International Baccalaureate + official school domain'),
  ('school', 'MEF International School', 'high_school', 'Turkey', 'İstanbul', 'https://www.mefis.k12.tr/istanbul/', array['MEF International School Istanbul', 'MEF IS Istanbul'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0048) — International Baccalaureate'),
  ('school', 'MEF International School, Izmir', 'high_school', 'Turkey', 'İzmir', 'https://www.mefis.k12.tr/izmir/', array['MEF International School Izmir', 'MEF International Schools, Izmir', 'MEFIS Izmir'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0049) — Official school + International Baccalaureate'),
  ('school', 'Bilkent Erzurum Laboratory School', 'high_school', 'Turkey', 'Erzurum', 'https://bels.k12.tr', array['BELS', 'Bilkent Erzurum Laboratuvar Okulları'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0050) — Official school + International Baccalaureate + Bilkent University'),
  ('school', 'BJK Kabataş Vakfı Özel Anadolu Lisesi', 'high_school', 'Turkey', 'İstanbul', 'https://www.bjkkabatasvakfiokullari.k12.tr/', array['BJK Kabataş Vakfı Okulları', 'BJK Kabataş Vakfı Anadolu Lisesi', 'BJK Kabataş Vakfı Private Anatolian High School'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0051) — Official school + International Baccalaureate'),
  ('school', 'Gaziantep Kolej Vakfı Cemil Alevli College', 'high_school', 'Turkey', 'Gaziantep', 'https://www.gkv.k12.tr/cemilalevli/', array['GKV Cemil Alevli Koleji', 'GKV Özel Cemil Alevli Koleji', 'Gaziantep College Foundation Cemil Alevli College'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0052) — Official school + International Baccalaureate'),
  ('school', 'Kültür2000', 'high_school', 'Turkey', 'İstanbul', 'https://www.kultur2000.k12.tr/', array['Kültür2000 Koleji', 'Kultur2000'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0053) — Official school + International Baccalaureate'),
  ('school', 'Sezin Okulu', 'high_school', 'Turkey', 'İstanbul', 'https://www.sezin.k12.tr/', array['THE SEZIN SCHOOL', 'Sezin School', 'Sezin'], 'verified', 'ORYN Canonical App Data Pack — Verified 2026-08-15 (TRSCH-0054) — Official school + International Baccalaureate')
on conflict (category, lower(canonical_name), coalesce(country, ''), coalesce(city, '')) do nothing;

-- ---------- Universities (GUNI, QS 2027 ranking — 77 new of 98, 21 already exist in supabase/seed.sql + seed_drive_batch1.sql by name+country match) ----------
insert into public.universities (name, country, city, institution_type, website_url, aliases, data_confidence, data_status)
values
  ('California Institute of Technology', 'United States', 'Pasadena, CA', 'University', 'https://www.admissions.caltech.edu/', array['Caltech'], 'high', 'fresh'),
  ('UCL', 'United Kingdom', 'London', 'University', 'https://www.ucl.ac.uk/', '{}', 'high', 'fresh'),
  ('National University of Singapore', 'Singapore', 'Singapore', 'University', 'https://www.nus.edu.sg/oam/', array['NUS'], 'high', 'fresh'),
  ('The University of Hong Kong', 'Hong Kong SAR', 'Hong Kong', 'University', 'https://www.admissions.hku.hk/', '{}', 'high', 'fresh'),
  ('Nanyang Technological University, Singapore', 'Singapore', 'Singapore', 'University', 'https://www.ntu.edu.sg/admissions/undergraduate/', array['NTU Singapore'], 'high', 'fresh'),
  ('Peking University', 'China', 'Beijing', 'University', 'https://www.isd.pku.edu.cn/en/', '{}', 'high', 'fresh'),
  ('Tsinghua University', 'China', 'Beijing', 'University', 'https://international.join-tsinghua.edu.cn/', '{}', 'high', 'fresh'),
  ('Cornell University', 'United States', 'Ithaca, NY', 'University', 'https://admissions.cornell.edu/', '{}', 'high', 'fresh'),
  ('The Chinese University of Hong Kong', 'Hong Kong SAR', 'Hong Kong', 'University', 'https://admission.cuhk.edu.hk/', array['CUHK'], 'high', 'fresh'),
  ('The University of New South Wales', 'Australia', 'Sydney', 'University', 'https://www.unsw.edu.au/', array['UNSW Sydney'], 'high', 'fresh'),
  ('Johns Hopkins University', 'United States', 'Baltimore, MD', 'University', 'https://apply.jhu.edu/', '{}', 'high', 'fresh'),
  ('EPFL – École polytechnique fédérale de Lausanne', 'Switzerland', 'Lausanne', 'University', 'https://www.epfl.ch/en/', '{}', 'high', 'fresh'),
  ('The University of Melbourne', 'Australia', 'Melbourne', 'University', 'https://study.unimelb.edu.au/', '{}', 'high', 'fresh'),
  ('Fudan University', 'China', 'Shanghai', 'University', 'https://iso.fudan.edu.cn/isoenglish/', '{}', 'high', 'fresh'),
  ('The University of Sydney', 'Australia', 'Sydney', 'University', 'https://www.sydney.edu.au/study/', '{}', 'high', 'fresh'),
  ('Australian National University', 'Australia', 'Canberra', 'University', 'https://study.anu.edu.au/', array['ANU'], 'high', 'fresh'),
  ('Monash University', 'Australia', 'Melbourne', 'University', 'https://www.monash.edu/study/', '{}', 'high', 'fresh'),
  ('The Hong Kong University of Science and Technology', 'Hong Kong SAR', 'Hong Kong', 'University', 'https://join.hkust.edu.hk/', array['HKUST'], 'high', 'fresh'),
  ('Université PSL', 'France', 'Paris', 'University', 'https://psl.eu/', '{}', 'high', 'fresh'),
  ('The University of Edinburgh', 'United Kingdom', 'Edinburgh', 'University', 'https://www.ed.ac.uk/', '{}', 'high', 'fresh'),
  ('Shanghai Jiao Tong University', 'China', 'Shanghai', 'University', 'https://en.sjtu.edu.cn/', '{}', 'high', 'fresh'),
  ('King''s College London', 'United Kingdom', 'London', 'University', 'https://www.kcl.ac.uk/', '{}', 'high', 'fresh'),
  ('Seoul National University', 'South Korea', 'Seoul', 'University', 'https://en.snu.ac.kr/', '{}', 'high', 'fresh'),
  ('The University of Tokyo', 'Japan', 'Tokyo', 'University', 'https://www.u-tokyo.ac.jp/en/', '{}', 'high', 'fresh'),
  ('The University of Manchester', 'United Kingdom', 'Manchester', 'University', 'https://www.manchester.ac.uk/', '{}', 'high', 'fresh'),
  ('The University of Queensland', 'Australia', 'Brisbane', 'University', 'https://www.uq.edu.au/', '{}', 'high', 'fresh'),
  ('Yonsei University', 'South Korea', 'Seoul', 'University', 'https://www.yonsei.ac.kr/en_sc/', '{}', 'high', 'fresh'),
  ('Institut Polytechnique de Paris', 'France', 'Paris', 'University', 'https://www.ip-paris.fr/en', '{}', 'high', 'fresh'),
  ('Northwestern University', 'United States', 'Evanston, IL', 'University', 'https://www.northwestern.edu/', '{}', 'high', 'fresh'),
  ('University of British Columbia', 'Canada', 'Vancouver', 'University', 'https://www.ubc.ca/', '{}', 'high', 'fresh'),
  ('Zhejiang University', 'China', 'Hangzhou', 'University', 'https://www.zju.edu.cn/english/', '{}', 'high', 'fresh'),
  ('University of California, Los Angeles', 'United States', 'Los Angeles, CA', 'University', 'https://www.ucla.edu/', array['UCLA'], 'high', 'fresh'),
  ('The Hong Kong Polytechnic University', 'Hong Kong SAR', 'Hong Kong', 'University', 'https://www.polyu.edu.hk/', '{}', 'high', 'fresh'),
  ('University of Michigan-Ann Arbor', 'United States', 'Ann Arbor, MI', 'University', 'https://umich.edu/', '{}', 'high', 'fresh'),
  ('City University of Hong Kong', 'Hong Kong SAR', 'Hong Kong', 'University', 'https://www.cityu.edu.hk/', array['CityUHK'], 'high', 'fresh'),
  ('Korea University', 'South Korea', 'Seoul', 'University', 'https://www.korea.edu/en/index.do', '{}', 'high', 'fresh'),
  ('National Taiwan University', 'Taiwan', 'Taipei', 'University', 'https://www.ntu.edu.tw/english/', array['NTU'], 'high', 'fresh'),
  ('Carnegie Mellon University', 'United States', 'Pittsburgh, PA', 'University', 'https://www.cmu.edu/', '{}', 'high', 'fresh'),
  ('Universiti Malaya', 'Malaysia', 'Kuala Lumpur', 'University', 'https://www.um.edu.my/', array['UM'], 'high', 'fresh'),
  ('University of Bristol', 'United Kingdom', 'Bristol', 'University', 'https://www.bristol.ac.uk/', '{}', 'high', 'fresh'),
  ('KU Leuven', 'Belgium', 'Leuven', 'University', 'https://www.kuleuven.be/english/', '{}', 'high', 'fresh'),
  ('Ludwig-Maximilians-Universität München', 'Germany', 'Munich', 'University', 'https://www.lmu.de/en/', '{}', 'high', 'fresh'),
  ('The London School of Economics and Political Science', 'United Kingdom', 'London', 'University', 'https://www.lse.ac.uk/', array['LSE'], 'high', 'fresh'),
  ('KFUPM', 'Saudi Arabia', 'Dhahran', 'University', null, '{}', 'high', 'fresh'),
  ('Kyoto University', 'Japan', 'Kyoto', 'University', 'https://www.kyoto-u.ac.jp/en/', '{}', 'high', 'fresh'),
  ('KAIST', 'South Korea', 'Daejeon', 'University', 'https://www.kaist.ac.kr/en/', '{}', 'high', 'fresh'),
  ('Brown University', 'United States', 'Providence, RI', 'University', 'https://www.brown.edu/', '{}', 'high', 'fresh'),
  ('The University of Auckland', 'New Zealand', 'Auckland', 'University', 'https://www.auckland.ac.nz/', '{}', 'high', 'fresh'),
  ('University of Birmingham', 'United Kingdom', 'Birmingham', 'University', null, '{}', 'high', 'fresh'),
  ('Duke University', 'United States', 'Durham, NC', 'University', null, '{}', 'high', 'fresh'),
  ('Lund University', 'Sweden', 'Lund', 'University', 'https://www.lunduniversity.lu.se/', '{}', 'high', 'fresh'),
  ('University of Texas at Austin', 'United States', 'Austin, TX', 'University', null, '{}', 'high', 'fresh'),
  ('Sorbonne University', 'France', 'Paris', 'University', null, '{}', 'high', 'fresh'),
  ('University of Illinois Urbana-Champaign', 'United States', 'Champaign, IL', 'University', null, '{}', 'high', 'fresh'),
  ('Trinity College Dublin, The University of Dublin', 'Ireland', 'Dublin', 'University', null, '{}', 'high', 'fresh'),
  ('Université Paris-Saclay', 'France', 'Paris', 'University', null, '{}', 'high', 'fresh'),
  ('The University of Western Australia', 'Australia', 'Perth', 'University', null, '{}', 'high', 'fresh'),
  ('University of Leeds', 'United Kingdom', 'Leeds', 'University', null, '{}', 'high', 'fresh'),
  ('Adelaide University', 'Australia', 'Adelaide', 'University', null, '{}', 'high', 'fresh'),
  ('University of Glasgow', 'United Kingdom', 'Glasgow', 'University', null, '{}', 'high', 'fresh'),
  ('University of California, San Diego', 'United States', 'San Diego, CA', 'University', null, array['UCSD'], 'high', 'fresh'),
  ('KTH Royal Institute of Technology', 'Sweden', 'Stockholm', 'University', null, '{}', 'high', 'fresh'),
  ('The University of Sheffield', 'United Kingdom', 'Sheffield', 'University', null, '{}', 'high', 'fresh'),
  ('Universidad de Buenos Aires', 'Argentina', 'Buenos Aires', 'University', null, array['UBA'], 'high', 'fresh'),
  ('Durham University', 'United Kingdom', 'Durham', 'University', null, '{}', 'high', 'fresh'),
  ('Universität Heidelberg', 'Germany', 'Heidelberg', 'University', null, '{}', 'high', 'fresh'),
  ('The University of Technology Sydney', 'Australia', 'Sydney', 'University', null, array['UTS'], 'high', 'fresh'),
  ('Uppsala University', 'Sweden', 'Uppsala', 'University', null, '{}', 'high', 'fresh'),
  ('Nanjing University', 'China', 'Nanjing', 'University', null, '{}', 'high', 'fresh'),
  ('University of Copenhagen', 'Denmark', 'Copenhagen', 'University', null, '{}', 'high', 'fresh'),
  ('Pennsylvania State University', 'United States', 'University Park, PA', 'University', null, '{}', 'high', 'fresh'),
  ('University of Washington', 'United States', 'Seattle, WA', 'University', null, '{}', 'high', 'fresh'),
  ('Boston University', 'United States', 'Boston, MA', 'University', null, '{}', 'high', 'fresh'),
  ('The University of Osaka', 'Japan', 'Osaka', 'University', null, '{}', 'high', 'fresh'),
  ('University of Alberta', 'Canada', 'Edmonton', 'University', null, '{}', 'high', 'fresh'),
  ('Institute of Science Tokyo', 'Japan', 'Tokyo', 'University', null, '{}', 'high', 'fresh'),
  ('University of Nottingham', 'United Kingdom', 'Nottingham', 'University', null, '{}', 'high', 'fresh')
on conflict (lower(name), country) do nothing;

-- Alias enrichment for 3 already-existing universities (explicit parenthetical abbreviation in the source, e.g. "(MIT)")
update public.universities set aliases = array_append(aliases, 'MIT') where lower(name) = lower('Massachusetts Institute of Technology') and country = 'United States' and not ('MIT' = any(aliases));
update public.universities set aliases = array_append(aliases, 'UCB') where lower(name) = lower('University of California, Berkeley') and country = 'United States' and not ('UCB' = any(aliases));
update public.universities set aliases = array_append(aliases, 'NYU') where lower(name) = lower('New York University') and country = 'United States' and not ('NYU' = any(aliases));

-- ---------- Opportunity aliases (5 of 7 usable — 2 excluded: canonical_opportunity_id not in the 16-row official-current set) ----------
-- Matched by exact title — a safe no-op if this batch's existing `opportunities` rows
-- use a differently-worded title than this corpus's own canonical name; never guesses.
update public.opportunities set aliases = array_append(aliases, '67th London International Youth Science Forum (LIYSF) - 2026') where title = 'London International Youth Science Forum (LIYSF) 2027' and not ('67th London International Youth Science Forum (LIYSF) - 2026' = any(aliases));
update public.opportunities set aliases = array_append(aliases, 'HMMT') where title = 'HMMT Season 30 — November 2026 / February 2027' and not ('HMMT' = any(aliases));
update public.opportunities set aliases = array_append(aliases, 'The Earth Prize Competition') where title = 'The Earth Prize 2027' and not ('The Earth Prize Competition' = any(aliases));
update public.opportunities set aliases = array_append(aliases, 'Wharton Global High School Investment Competition') where title = 'Wharton Global High School Investment Competition 2026-2027' and not ('Wharton Global High School Investment Competition' = any(aliases));
update public.opportunities set aliases = array_append(aliases, 'AMC - AIME') where title = 'MAA AMC 10 / AMC 12 2026-2027' and not ('AMC - AIME' = any(aliases));
