/** Suggestions only (SuggestInput never rejects a typed value) — skills are genuinely
 * open-ended, this just covers the common ones so "Python"/"python"/"Python Programming"
 * converge more often than not. */
export const SKILL_NAME_SUGGESTIONS: string[] = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C++",
  "C",
  "C#",
  "SQL",
  "R",
  "MATLAB",
  "HTML/CSS",
  "Excel",
  "Data Analysis",
  "Machine Learning",
  "Public Speaking",
  "Debate",
  "Creative Writing",
  "Technical Writing",
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Music Production",
  "Piano",
  "Guitar",
  "Violin",
  "Painting",
  "Statistics",
  "Financial Modeling",
  "Accounting",
  "Project Management",
  "Leadership",
  "Teamwork",
  "Negotiation",
  "Sales",
  "Marketing",
  "Social Media Management",
  "Event Planning",
  "Tutoring",
  "Translation",
  "Research",
  "Laboratory Techniques",
  "CAD",
  "3D Modeling",
  "Robotics",
  "Arduino",
  "Web Development",
  "App Development",
  "UX/UI Design",
];
