/** Suggestions only — a genuinely closed-ish list of common school/club sports, not
 * exhaustive (SuggestInput's typed-text fallback covers anything missing). */
export const SPORT_NAME_SUGGESTIONS: string[] = [
  "Soccer",
  "Basketball",
  "Volleyball",
  "Swimming",
  "Track and Field",
  "Cross Country",
  "Tennis",
  "Table Tennis",
  "Badminton",
  "Golf",
  "Baseball",
  "Softball",
  "American Football",
  "Rugby",
  "Field Hockey",
  "Ice Hockey",
  "Wrestling",
  "Fencing",
  "Gymnastics",
  "Cheerleading",
  "Rowing",
  "Sailing",
  "Cycling",
  "Skiing",
  "Snowboarding",
  "Martial Arts",
  "Taekwondo",
  "Judo",
  "Karate",
  "Boxing",
  "Water Polo",
  "Diving",
  "Archery",
  "Squash",
  "Lacrosse",
  "Handball",
  "Chess",
  "Esports",
];
