-- Adds one nullable-in-spirit, not-null-in-practice column so a degraded advisor reply's
-- disclosure survives a page reload. Written as 0087, NOT applied -- house pattern (0076,
-- 0086); renumbered to 0088 during merge, a real collision with oryn-d0's own 0087
-- (notifications_new_opportunity_dedupe), and applied to this database 2026-09-02, among 13
-- migrations the founder ran while the fleet was paused. lib/supabase/errors.ts's
-- isUndefinedColumnError degrades every write that names this column until it lands, so the
-- app was correct before this ran here and stays correct on any environment where it hasn't
-- run yet -- a fresh Supabase project replays every migration in order, and there is a real
-- window where this one specifically isn't there yet.
--
-- Why this is a real column and not derived from ai_usage.degraded (0076, also unapplied):
-- there is no correlation key between an advisor_messages row and the ai_usage row its own
-- generation logged. logAIUsage's insert never returns its own id, and the two tables share
-- only (user_id, feature, approximate created_at) -- a timestamp-proximity join is a guess,
-- not a derivation, and this feature exists specifically so a degrade disclosure is something
-- Oryn can stand behind later, not something inferred after the fact. Established this
-- 2026-09-02 before writing this migration, per CEO's own instruction to check first.
--
-- Why `not null default false` is still honest for the students this defaults onto: every
-- row that predates this column gets `false`, which this codebase's only consumer
-- (features/advisor/advisor-chat.tsx: `message.degraded ? <note> : null`) renders identically
-- to "unknown" -- nothing shown. No surface anywhere asserts "we confirmed this reply was NOT
-- degraded"; the column only ever answers "should the note render," and for a message written
-- before this column existed the honest answer to that question is no, not a guess either way.
alter table public.advisor_messages
  add column if not exists degraded boolean not null default false;

comment on column public.advisor_messages.degraded is
  'True when this specific assistant reply was generated by the degraded (cheaper) model -- lib/ai/advisor-chat.ts''s AdvisorReply.degraded, persisted at write time so the disclosure in the UI survives a reload. False for every row written before this column existed, which is indistinguishable from "unknown" to every current consumer (the note simply does not render) -- never read as a confirmed "this reply was not degraded".';
